import { REASONING_EFFORT_OPTIONS } from "../types.js";

import type { SettingsFieldDefinition, SettingsSectionDefinition } from "./settings-types.js";
import { SECTION_GROUPS } from "./settings-types.js";
import { getValueAtPath } from "./settings-paths.js";

/** Static section definitions that do not depend on runtime effective config. */
function staticSections(): SettingsSectionDefinition[] {
  return [
    {
      id: "tracker",
      groupId: SECTION_GROUPS.SETUP.id,
      startHere: true,
      title: "Tracker",
      description: "Connect Risoluto to your issue tracker and choose which states count as active or done.",
      badge: "Start here",
      prefixes: ["tracker"],
      saveLabel: "Save tracker",
      fields: [
        {
          path: "tracker.kind",
          label: "Issue tracker",
          kind: "select",
          tier: "essential",
          group: "Connection",
          groupDescription: "Choose the tracker Risoluto should read work from.",
          options: [{ value: "linear", label: "Linear" }],
          defaultValue: "linear",
        },
        {
          path: "tracker.endpoint",
          label: "Endpoint override",
          kind: "text",
          tier: "expert",
          group: "Advanced connection",
          groupDescription: "Only change this if you route tracker traffic through a custom endpoint.",
          hint: "Only change if routing through a proxy.",
          defaultValue: "https://api.linear.app/graphql",
        },
        {
          path: "tracker.project_slug",
          label: "Linear project",
          kind: "text",
          tier: "essential",
          group: "Connection",
          hint: "The project Risoluto dispatches from.",
          actionLabel: "Browse",
          actionKind: "browse-linear-projects",
          validation: { required: true },
        },
        {
          path: "tracker.active_states",
          label: "States that mean work is active",
          kind: "list",
          tier: "essential",
          group: "Workflow meaning",
          groupDescription: "Tell Risoluto which tracker states mean an issue is ready for work.",
          hint: "Issues in these states are ready for agents.",
          placeholder: "Todo\nIn Progress",
          defaultValue: "Todo, In Progress",
        },
        {
          path: "tracker.terminal_states",
          label: "States that mean work is done",
          kind: "list",
          tier: "essential",
          group: "Workflow meaning",
          hint: "Issues here are no longer active.",
          placeholder: "Done\nCanceled",
          defaultValue: "Done, Completed, Closed, Canceled, Duplicate",
        },
      ],
    },
    {
      id: "model-provider-auth",
      groupId: SECTION_GROUPS.AGENT.id,
      title: "Model provider and access",
      description: "Choose which model Risoluto uses, how it signs in, and where requests go.",
      badge: "Core runtime",
      prefixes: ["codex.model", "codex.reasoning_effort", "codex.auth", "codex.provider"],
      saveLabel: "Save provider settings",
      fields: [
        {
          path: "codex.model",
          label: "Default model",
          kind: "text",
          tier: "essential",
          group: "Default model",
          groupDescription: "Set the model Risoluto should use unless an issue override is saved.",
          hint: "Model agents use unless overridden per-issue.",
          defaultValue: "gpt-5.4",
          validation: { required: true },
        },
        {
          path: "codex.reasoning_effort",
          label: "Reasoning depth",
          kind: "select",
          tier: "essential",
          group: "Default model",
          options: REASONING_EFFORT_OPTIONS.map((value) => ({ value, label: value })),
          hint: "Higher = more thorough but slower and costlier.",
          defaultValue: "high",
        },
        {
          path: "codex.auth.mode",
          label: "Sign-in method",
          kind: "select",
          tier: "essential",
          group: "Sign-in",
          groupDescription:
            "How the agent signs in to the model provider. Credentials are read from the folder below (default: ~/.codex/auth.json).",
          options: [
            { value: "api_key", label: "API key (from env or auth.json)" },
            { value: "openai_login", label: "OpenAI login (browser sign-in)" },
          ],
          hint: "API key sign-in reads OPENAI_API_KEY or ~/.codex/auth.json. OpenAI login uses a browser flow.",
          defaultValue: "api_key",
        },
        {
          path: "codex.auth.source_home",
          label: "Credentials folder",
          kind: "text",
          tier: "expert",
          group: "Sign-in",
          hint: "Folder containing auth.json and related credentials. Default: ~/.codex.",
          defaultValue: "~/.codex",
        },
        {
          path: "codex.provider.id",
          label: "Provider key",
          kind: "text",
          tier: "expert",
          group: "Provider routing",
          groupDescription:
            "Only fill these in when routing agent requests through a custom or OpenAI-compatible provider.",
          placeholder: "custom",
          hint: 'Short provider identifier (for example, "azure").',
        },
        {
          path: "codex.provider.name",
          label: "Provider name",
          kind: "text",
          tier: "expert",
          group: "Provider routing",
          hint: "Human-readable provider name.",
        },
        {
          path: "codex.provider.base_url",
          label: "API base URL",
          kind: "text",
          tier: "expert",
          group: "Provider routing",
          hint: "Override the default OpenAI endpoint.",
        },
        {
          path: "codex.provider.env_key",
          label: "API key env var",
          kind: "text",
          tier: "expert",
          group: "Provider routing",
          redact: true,
          hint: "Environment variable holding the API key.",
        },
        {
          path: "codex.provider.env_key_instructions",
          label: "Setup instructions",
          kind: "textarea",
          tier: "expert",
          group: "Provider routing",
          hint: "Notes for operators setting up this provider.",
        },
        {
          path: "codex.provider.wire_api",
          label: "API protocol",
          kind: "text",
          tier: "expert",
          group: "Provider routing",
          placeholder: "responses",
          hint: "Wire protocol. Leave blank for default.",
          defaultValue: "responses",
        },
        {
          path: "codex.provider.requires_openai_auth",
          label: "Uses OpenAI login",
          kind: "boolean",
          tier: "expert",
          group: "Provider routing",
          hint: "Enable if provider piggybacks on OpenAI login.",
          defaultValue: "false",
        },
        {
          path: "codex.provider.http_headers",
          label: "Custom HTTP headers",
          kind: "json",
          tier: "expert",
          group: "Provider routing",
          hint: "Static headers sent with every API request.",
          defaultValue: "{}",
        },
        {
          path: "codex.provider.env_http_headers",
          label: "Header env vars",
          kind: "json",
          tier: "expert",
          group: "Provider routing",
          hint: "Map of header names to env var names.",
          defaultValue: "{}",
        },
        {
          path: "codex.provider.query_params",
          label: "Query parameters",
          kind: "json",
          tier: "expert",
          group: "Provider routing",
          hint: "Extra URL query parameters.",
          defaultValue: "{}",
        },
      ],
    },
    {
      id: "sandbox",
      groupId: SECTION_GROUPS.AGENT.id,
      title: "Sandbox",
      description: "Choose how Risoluto runs code and which safety limits it applies.",
      badge: "Execution safety",
      prefixes: ["codex.approval_policy", "codex.thread_sandbox", "codex.turn_sandbox_policy", "codex.sandbox"],
      saveLabel: "Save sandbox",
      fields: [
        {
          path: "codex.approval_policy",
          label: "Approval policy",
          kind: "select",
          tier: "essential",
          group: "Safety",
          groupDescription: "Decide which actions need explicit approval before they run.",
          options: [
            { value: "never", label: "Never — auto-approve everything" },
            { value: "on-request", label: "On request — approve when agent asks" },
            { value: "on-failure", label: "On failure — approve after errors" },
            { value: "untrusted", label: "Untrusted — approve all actions" },
          ],
          hint: "Controls when the agent pauses to ask for approval.",
          defaultValue: "never",
        },
        {
          path: "codex.thread_sandbox",
          label: "Sandbox mode",
          kind: "select",
          tier: "essential",
          group: "Container",
          groupDescription: "Choose the default sandbox mode and container image for each turn.",
          options: [
            { value: "workspace-write", label: "Workspace write (recommended)" },
            { value: "workspace-read", label: "Workspace read-only" },
            { value: "none", label: "None — no sandboxing" },
          ],
          hint: "How much filesystem access the agent has inside the container.",
          defaultValue: "workspace-write",
        },
        {
          path: "codex.sandbox.image",
          label: "Container image",
          kind: "text",
          tier: "essential",
          group: "Container",
          hint: "Docker image for sandboxed runs. Default: risoluto-codex:latest",
          placeholder: "risoluto-codex:latest",
          defaultValue: "risoluto-codex:latest",
        },
        {
          path: "codex.sandbox.egress_allowlist",
          label: "Allowed outbound hosts",
          kind: "list",
          tier: "standard",
          group: "Container",
          hint: "Domains the sandbox can reach.",
          placeholder: "github.com\nnpm.org",
          defaultValue: "[]",
        },
        {
          path: "codex.sandbox.extra_mounts",
          label: "Extra volume mounts",
          kind: "list",
          tier: "standard",
          group: "Container",
          hint: "Host paths mounted inside the sandbox.",
        },
        {
          path: "codex.sandbox.env_passthrough",
          label: "Environment variables for agents",
          kind: "list",
          tier: "standard",
          group: "Container",
          hint: "Type a variable name (e.g. LINEAR_API_KEY) and press Enter to add it. These host env vars are passed into the sandbox.",
          placeholder: "MY_ENV_VAR",
        },
        {
          path: "codex.sandbox.network",
          label: "Network mode",
          kind: "text",
          tier: "expert",
          group: "Container",
          hint: "Docker network mode.",
        },
        {
          path: "codex.turn_sandbox_policy",
          label: "Turn policy",
          kind: "json",
          tier: "expert",
          group: "Safety",
          hint: "Per-turn sandbox policy override.",
          defaultValue: '{"type":"inherit"}',
        },
        {
          path: "codex.sandbox.security.no_new_privileges",
          label: "No new privileges",
          kind: "boolean",
          tier: "expert",
          group: "Safety",
          hint: "Prevent privilege escalation.",
          defaultValue: "true",
        },
        {
          path: "codex.sandbox.security.drop_capabilities",
          label: "Drop capabilities",
          kind: "boolean",
          tier: "expert",
          group: "Safety",
          hint: "Remove Linux capabilities.",
          defaultValue: "true",
        },
        {
          path: "codex.sandbox.security.gvisor",
          label: "Kernel isolation",
          kind: "boolean",
          tier: "expert",
          group: "Safety",
          hint: "Run inside a user-space kernel for stronger isolation. Slower.",
          defaultValue: "false",
        },
        {
          path: "codex.sandbox.security.seccomp_profile",
          label: "System call filter",
          kind: "text",
          tier: "expert",
          group: "Safety",
          hint: "Path to Linux seccomp profile. Leave blank for container default.",
        },
        {
          path: "codex.sandbox.resources.memory",
          label: "Memory limit",
          kind: "text",
          tier: "expert",
          group: "Resources",
          groupDescription: "Optional resource caps for each sandboxed run.",
          hint: "Hard memory cap.",
          defaultValue: "4g",
        },
        {
          path: "codex.sandbox.resources.memory_reservation",
          label: "Memory reservation",
          kind: "text",
          tier: "expert",
          group: "Resources",
          hint: "Soft memory limit \u2014 system tries to honor.",
          defaultValue: "1g",
        },
        {
          path: "codex.sandbox.resources.memory_swap",
          label: "Swap limit",
          kind: "text",
          tier: "expert",
          group: "Resources",
          hint: "Swap limit. -1 = unlimited.",
          defaultValue: "4g",
        },
        {
          path: "codex.sandbox.resources.cpus",
          label: "CPU limit",
          kind: "text",
          tier: "expert",
          group: "Resources",
          hint: "Max CPUs allocated.",
          defaultValue: "2.0",
        },
        {
          path: "codex.sandbox.resources.tmpfs_size",
          label: "Temp storage",
          kind: "text",
          tier: "expert",
          group: "Resources",
          hint: "In-memory scratch space per run.",
          defaultValue: "512m",
        },
        {
          path: "codex.sandbox.logs.driver",
          label: "Log driver",
          kind: "text",
          tier: "expert",
          group: "Logging",
          groupDescription: "Container log rotation settings.",
          hint: "Container log driver.",
          defaultValue: "json-file",
        },
        {
          path: "codex.sandbox.logs.max_size",
          label: "Log max size",
          kind: "text",
          tier: "expert",
          group: "Logging",
          hint: "Max size per log file.",
          defaultValue: "50m",
        },
        {
          path: "codex.sandbox.logs.max_file",
          label: "Max log files",
          kind: "number",
          tier: "expert",
          group: "Logging",
          hint: "Number of rotated log files.",
          defaultValue: "3",
        },
      ],
    },
    {
      id: "agent",
      groupId: SECTION_GROUPS.AGENT.id,
      title: "Agent",
      description: "Set how many issues run at once, how long each run may take, and when to retry.",
      badge: "Core runtime",
      prefixes: ["agent"],
      saveLabel: "Save agent settings",
      fields: [
        {
          path: "agent.max_concurrent_agents",
          label: "Parallel agents",
          kind: "number",
          tier: "essential",
          group: "Throughput",
          groupDescription: "Control how much work Risoluto runs in parallel.",
          hint: "How many issues to work on at once.",
          defaultValue: "10",
          validation: { min: 1, max: 50 },
        },
        {
          path: "agent.max_turns",
          label: "Max turns",
          kind: "number",
          tier: "essential",
          group: "Throughput",
          hint: "Agent stops after this many conversation turns.",
          defaultValue: "20",
          validation: { min: 1, max: 500 },
        },
        {
          path: "agent.success_state",
          label: "Completion state",
          kind: "text",
          tier: "essential",
          group: "Throughput",
          hint: 'Move issues to this state after success (e.g. "Done"). Blank means no transition.',
        },
        {
          path: "agent.stall_timeout_ms",
          label: "Agent stall timeout",
          kind: "number",
          tier: "standard",
          group: "Continuation",
          groupDescription: "Prevent long-running issues from looping forever without a stop signal.",
          hint: "Stop the agent after this much idle time. 0 disables the timeout.",
          unit: "ms",
          defaultValue: "1200000",
          validation: { min: 0 },
        },
        {
          path: "agent.max_continuation_attempts",
          label: "Max continuations",
          kind: "number",
          tier: "standard",
          group: "Continuation",
          hint: "How many extra turns to allow when no stop signal arrives.",
          defaultValue: "5",
          validation: { min: 0, max: 50 },
        },
        {
          path: "agent.max_concurrent_agents_by_state",
          label: "Concurrency by state",
          kind: "json",
          tier: "expert",
          group: "Retries",
          groupDescription: "Fine-tune concurrency and retry behavior.",
          hint: 'Per-state limits, e.g. {"in progress": 2}.',
          defaultValue: "{}",
        },
        {
          path: "agent.max_retry_backoff_ms",
          label: "Max retry backoff",
          kind: "number",
          tier: "expert",
          group: "Retries",
          hint: "Longest wait between retries.",
          unit: "ms",
          defaultValue: "300000",
          validation: { min: 0 },
        },
        {
          path: "system.selectedTemplateId",
          label: "Active Prompt Template",
          kind: "readonly",
          tier: "standard",
          group: "Prompt",
          groupDescription: "Control the Liquid template used for agent instructions.",
          hint: "The Liquid template used for agent instructions.",
          actionLabel: "Manage Templates",
          actionKind: "navigate-templates",
          editable: false,
        },
      ],
    },
    {
      id: "codex-timeouts",
      groupId: SECTION_GROUPS.AGENT.id,
      mode: "advanced",
      title: "Agent timeouts",
      description: "Set how long Risoluto waits at each stage of the agent lifecycle.",
      badge: "Performance",
      prefixes: [
        "codex.command",
        "codex.startup_timeout_ms",
        "codex.read_timeout_ms",
        "codex.turn_timeout_ms",
        "codex.drain_timeout_ms",
        "codex.stall_timeout_ms",
      ],
      saveLabel: "Save timeout settings",
      fields: [
        {
          path: "codex.command",
          label: "Agent command",
          kind: "text",
          tier: "standard",
          hint: "Command Risoluto uses to launch agents.",
          defaultValue: "codex app-server",
        },
        {
          path: "codex.startup_timeout_ms",
          label: "Startup timeout",
          kind: "number",
          tier: "standard",
          hint: "Wait time for agent process to start.",
          unit: "ms",
          defaultValue: "30000",
          validation: { min: 0 },
        },
        {
          path: "codex.read_timeout_ms",
          label: "Read timeout",
          kind: "number",
          tier: "standard",
          hint: "Max wait for each response chunk.",
          unit: "ms",
          defaultValue: "5000",
          validation: { min: 0 },
        },
        {
          path: "codex.turn_timeout_ms",
          label: "Turn timeout",
          kind: "number",
          tier: "standard",
          hint: "Max time for a single agent turn.",
          unit: "ms",
          defaultValue: "3600000",
          validation: { min: 0 },
        },
        {
          path: "codex.drain_timeout_ms",
          label: "Drain timeout",
          kind: "number",
          tier: "standard",
          hint: "Wait time for graceful shutdown.",
          unit: "ms",
          defaultValue: "2000",
          validation: { min: 0 },
        },
        {
          path: "codex.stall_timeout_ms",
          label: "Stall detection",
          kind: "number",
          tier: "standard",
          hint: "Kill if agent produces no output for this long.",
          unit: "ms",
          defaultValue: "300000",
        },
      ],
    },
    {
      id: "workspace",
      groupId: SECTION_GROUPS.AGENT.id,
      mode: "advanced",
      title: "Workspace",
      description: "Choose where Risoluto creates issue workspaces and how lifecycle hooks run.",
      badge: "Infrastructure",
      prefixes: ["workspace", "hooks.timeout_ms"],
      saveLabel: "Save workspace settings",
      fields: [
        {
          path: "workspace.root",
          label: "Workspace root",
          kind: "text",
          tier: "essential",
          group: "Management",
          groupDescription: "Where and how Risoluto creates per-issue workspaces.",
          hint: "Where per-issue workspaces are created.",
          defaultValue: "../risoluto-workspaces",
        },
        {
          path: "workspace.strategy",
          label: "Strategy",
          kind: "select",
          tier: "essential",
          group: "Management",
          options: [
            { value: "directory", label: "Directory (plain folders)" },
            { value: "worktree", label: "Worktree (git worktrees)" },
          ],
          hint: "directory = plain folders. worktree = git worktrees.",
          defaultValue: "directory",
        },
        {
          path: "workspace.branch_prefix",
          label: "Branch prefix",
          kind: "text",
          tier: "essential",
          group: "Management",
          hint: "Prefix for auto-created branches.",
          defaultValue: "risoluto/",
        },
        {
          path: "workspace.hooks.after_create",
          label: "After-create hook",
          kind: "text",
          tier: "expert",
          group: "Hooks",
          groupDescription: "Shell commands that run at workspace lifecycle events.",
          hint: "Shell command after workspace creation.",
        },
        {
          path: "workspace.hooks.before_run",
          label: "Before-run hook",
          kind: "text",
          tier: "expert",
          group: "Hooks",
          hint: "Shell command before agent starts.",
        },
        {
          path: "workspace.hooks.after_run",
          label: "After-run hook",
          kind: "text",
          tier: "expert",
          group: "Hooks",
          hint: "Shell command after agent finishes.",
        },
        {
          path: "workspace.hooks.before_remove",
          label: "Before-remove hook",
          kind: "text",
          tier: "expert",
          group: "Hooks",
          hint: "Shell command before workspace cleanup.",
        },
        {
          path: "hooks.timeout_ms",
          label: "Hook timeout",
          kind: "number",
          tier: "expert",
          group: "Hooks",
          hint: "Max time for any hook to run.",
          unit: "ms",
          defaultValue: "60000",
        },
      ],
    },
    {
      id: "repositories-github",
      groupId: SECTION_GROUPS.SETUP.id,
      title: "Repositories / GitHub",
      description: "Connect GitHub repos so Risoluto knows where to create branches and PRs.",
      badge: "Integration",
      prefixes: ["repos", "github"],
      saveLabel: "Save repository settings",
      fields: [
        {
          path: "repos",
          label: "Repository routing",
          kind: "json",
          tier: "essential",
          group: "Repositories",
          groupDescription: "Map Linear projects to GitHub repos so Risoluto knows where to create branches and PRs.",
          hint: 'JSON array: [{"match": "NIN-*", "github_repo": "org/repo", "base_branch": "main"}]. Each entry maps issue prefixes to a GitHub repo.',
          placeholder: '[{"match": "NIN-*", "github_repo": "org/repo", "base_branch": "main"}]',
        },
        {
          path: "github.api_base_url",
          label: "GitHub API base URL",
          kind: "text",
          tier: "expert",
          group: "GitHub Enterprise",
          groupDescription: "Only needed for GitHub Enterprise Server. Leave blank for github.com.",
          hint: "Override for GitHub Enterprise (e.g. https://github.corp.com/api/v3). Leave empty for github.com.",
          placeholder: "https://api.github.com",
        },
        {
          path: "github.token",
          label: "GitHub token",
          kind: "text",
          redact: true,
          hint: "Redacted after load for safety.",
        },
      ],
    },
    {
      id: "notifications",
      groupId: SECTION_GROUPS.NOTIFICATIONS.id,
      title: "Notifications",
      description:
        "Manage Slack here, then use overlay or API config for advanced channels, triggers, automations, and alerts.",
      badge: "Integration",
      prefixes: ["notifications"],
      saveLabel: "Save notifications",
      fields: [
        {
          path: "notifications.slack.verbosity",
          label: "Slack verbosity",
          kind: "select",
          options: ["off", "critical", "verbose"].map((value) => ({ value, label: value })),
          defaultValue: "off",
        },
        {
          path: "notifications.slack.webhook_url",
          label: "Slack webhook URL",
          kind: "text",
          redact: true,
          hint: "Existing webhook values stay redacted. Enter a new one to replace it.",
        },
      ],
    },
    {
      id: "workflow-stages",
      groupId: SECTION_GROUPS.SYSTEM.id,
      mode: "advanced",
      title: "Workflow stages",
      description: "Define custom pipeline stages if the default flow does not fit your workflow.",
      badge: "Advanced",
      prefixes: ["state_machine"],
      saveLabel: "Save workflow stages",
      fields: [
        { path: "state_machine.stages", label: "Stages", kind: "json", hint: "JSON array of stage definitions." },
        {
          path: "state_machine.transitions",
          label: "Transitions",
          kind: "json",
          hint: "JSON object keyed by source stage.",
        },
      ],
    },
    {
      id: "credentials",
      groupId: SECTION_GROUPS.SYSTEM.id,
      mode: "advanced",
      title: "Credentials",
      description: "Store the API keys and tokens Risoluto uses to reach external services.",
      badge: "Security",
      prefixes: ["secrets"],
      saveLabel: "Manage credentials",
      fields: [
        {
          path: "secrets",
          label: "Stored credentials",
          kind: "credential",
          hint: "Values are encrypted at rest. After saving, only the key name is visible \u2014 values remain write-only.",
        },
      ],
    },
  ];
}

/** Sections whose shape depends on the runtime effective config. */
function dynamicSections(effective: Record<string, unknown>): SettingsSectionDefinition[] {
  const featureFlagPath = getValueAtPath(effective, "feature_flags") !== undefined ? "feature_flags" : "flags";
  return [
    {
      id: "feature-flags",
      groupId: SECTION_GROUPS.SYSTEM.id,
      mode: "advanced",
      title: "Feature flags",
      description: "Turn on runtime feature flags when the backend exposes them.",
      badge: "Runtime dependent",
      prefixes: [featureFlagPath],
      saveLabel: "Save flags",
      fields: [
        getValueAtPath(effective, featureFlagPath) === undefined
          ? {
              path: "runtime.feature_flags",
              label: "Feature flags",
              kind: "readonly",
              hint: "Feature flag metadata not exposed yet.",
              editable: false,
            }
          : {
              path: featureFlagPath,
              label: "Feature flags",
              kind: "json",
              hint: "JSON object keyed by feature flag name.",
            },
      ],
    },
    {
      id: "runtime-paths",
      groupId: SECTION_GROUPS.SYSTEM.id,
      mode: "advanced",
      title: "Runtime and paths",
      description: "Polling interval, dashboard port, and read-only runtime details.",
      badge: "Runtime info",
      prefixes: ["polling", "server", "runtime"],
      saveLabel: "Save runtime settings",
      fields: [
        {
          path: "polling.interval_ms",
          label: "Poll interval",
          kind: "number",
          tier: "standard",
          hint: "How often Risoluto checks for new work.",
          unit: "ms",
          defaultValue: "15000",
        },
        {
          path: "server.port",
          label: "Dashboard port",
          kind: "number",
          tier: "standard",
          hint: "Port the web dashboard listens on.",
          defaultValue: "4000",
        },
        ...getRuntimeMetadataFields(effective),
      ],
    },
  ];
}

/** Build runtime metadata fields for the runtime-paths section. */
function getRuntimeMetadataFields(effective: Record<string, unknown>): SettingsFieldDefinition[] {
  const metadataPaths = [
    ["runtime.data_dir", "Data directory"],
    ["runtime.provider_summary", "Provider summary"],
  ] as const;
  return metadataPaths.map(([path, label]) => ({
    path,
    label,
    kind: "readonly" as const,
    hint:
      getValueAtPath(effective, path) === undefined
        ? "Runtime metadata not exposed yet."
        : "Read-only runtime metadata for operator confidence.",
    editable: false,
  }));
}

/**
 * Assemble all default section definitions.
 *
 * Static sections come first (tracker through credentials), then
 * dynamic sections whose shape depends on effective config values
 * (feature-flags, runtime-paths).
 */
export function buildDefaultSections(effective: Record<string, unknown>): SettingsSectionDefinition[] {
  const sections = staticSections();
  // Insert dynamic sections before the last entry (credentials) so
  // credentials stays at the bottom of the sidebar.
  const credentialsSection = sections.pop()!;
  return [...sections, ...dynamicSections(effective), credentialsSection];
}
